### ISSUE TITLE
Error creating world with custom chunk generator

### ISSUE THREAD

**Issue by khjxiaogu** [YUNG-GANG/YUNGs-API#18]
Using custom chunk generator handled by bukkit, cause an error, which stops further action to save world.
Maybe just ignore this excpetion and just ignore generation?
```
java.lang.UnsupportedOperationException: Cannot serialize CustomChunkGenerator
	at org.bukkit.craftbukkit.v1_16_R3.generator.CustomChunkGenerator.func_230347_a_(CustomChunkGenerator.java:212)
	at net.minecraft.world.gen.ChunkGenerator.yungsapi_getCodec(ChunkGenerator.java)
	at com.yungnickyoung.minecraft.yungsapi.init.YAModWorldgen.deepCopyDimensionalSpacing(YAModWorldgen.java:30)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraft.server.MinecraftServer.loadSpawn(MinecraftServer.java:1946)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createWorld(CraftServer.java:1086)
	at org.bukkit.Bukkit.createWorld(Bukkit.java:521)
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325)
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486)
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:288)
	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:125)
	at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296)
	at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
	at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:839)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:157)
```

**Comment by CorgiTaco** [comment]
Yung's API is a forge mod and cannot be used with bukkit
