### ISSUE TITLE
Yungs API Crashing 

### ISSUE THREAD

**Issue by cregooo** [YUNG-GANG/YUNGs-API#2]
So I'm using the Better mineshafts mod which obviously requires the Yungs Api mod to work, But when I would try to actually use the API mod it would cause my game to crash with the log saying "Process crashed with exit code 1" And I'm on forge 1.16.5

**Comment by yungnickyoung** [comment]
Can you provide the crashlog and latest.log?

**Comment by RealTenzFate** [comment]
Also getting the same issue, here is my crash log.

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 19/04/21 20:28
Description: Initializing game

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/client/audio/SoundEngine.func_148611_c(Lnet/minecraft/client/audio/ISound;)V @564: aload
  Reason:
    Type integer (current frame, locals[14]) is not assignable to reference type
  Current Frame:
    bci: @564
    flags: { }
    locals: { 'net/minecraft/client/audio/SoundEngine', 'net/minecraft/client/audio/ISound', 'net/minecraft/client/audio/SoundEventAccessor', 'net/minecraft/util/ResourceLocation', 'net/minecraft/client/audio/Sound', float, float, 'net/minecraft/util/SoundCategory', float, float, 'net/minecraft/client/audio/ISound$AttenuationType', integer, 'net/minecraft/util/math/vector/Vector3d', integer, integer, 'java/util/concurrent/CompletableFuture', 'net/minecraft/client/audio/ChannelManager$Entry' }
    stack: { 'net/minecraft/client/audio/ISound' }
  Bytecode:
    0x0000000: 2ab4 00f7 9902 8b2a 2bb8 0255 4c2b c602
    0x0000010: 812b b901 b701 0099 0278 2b2a b400 83b9
    0x0000020: 0259 0200 4d2b b902 5c01 004e 2cc7 0021
    0x0000030: b200 a42d b900 db02 0099 0256 b200 cbb2
    0x0000040: 0135 1302 5e2d b902 6004 00a7 0244 2bb9
    0x0000050: 0264 0100 3a04 1904 b202 68a6 0021 b200
    0x0000060: a42d b900 db02 0099 0228 b200 cbb2 0135
    0x0000070: 1302 6a2d b902 6004 00a7 0216 2bb9 026e
    0x0000080: 0100 3805 1705 0cb8 0274 1904 b602 7986
    0x0000090: 6a38 062b b902 0701 003a 072a 2bb7 01de
    0x00000a0: 3808 2a2b b701 e138 092b b902 7d01 003a
    0x00000b0: 0a2b b902 8001 0036 0b17 080b 959a 0022
    0x00000c0: 2bb9 0283 0100 9a00 19b2 00cb b201 3513
    0x00000d0: 0285 1904 b602 88b9 0227 0400 a701 b3bb
    0x00000e0: 01e3 592b b902 8901 002b b902 8a01 002b
    0x00000f0: b902 8b01 00b7 01f0 3a0c 2ab4 007d b902
    0x0000100: 8e01 009a 0071 150b 9a00 2119 0ab2 0292
    0x0000110: a500 192a b400 55b6 0296 190c b602 9a17
    0x0000120: 0617 066a 8d98 9c00 0704 a700 0403 360d
    0x0000130: 150d 9900 332a b400 7db9 01cf 0100 3a0e
    0x0000140: 190e b900 b901 0099 001b 190e b900 bd01
    0x0000150: 00c0 029c 3a0f 190f 2b2c b902 a003 00a7
    0x0000160: ffe1 a700 12b2 00cb b201 3513 02a2 2db9
    0x0000170: 0227 0400 2ab4 0055 b602 a50b 969d 0015
    0x0000180: b200 cbb2 0135 1302 a72d b902 2704 00a7
    0x0000190: 0100 2bb8 02a9 360d 1904 b602 ac36 0e2a
    0x00001a0: b400 5f19 04b6 02ac 9900 09b2 02b0 a700
    0x00001b0: 06b2 02b3 b602 b73a 0f19 0fb6 02ba c000
    0x00001c0: 073a 1019 10c7 0011 b200 cb13 02bc b902
    0x00001d0: bf02 00a7 00bc b200 cbb2 0135 1302 c119
    0x00001e0: 04b6 0288 2db9 02c4 0500 2ab4 007b 2b2a
    0x00001f0: b401 af10 1460 b802 1db9 0221 0300 572a
    0x0000200: b400 672b 1910 b902 2103 0057 2ab4 006f
    0x0000210: 1907 2bb9 02c6 0300 5719 1017 0917 0819
    0x0000220: 0a17 0615 0d15 0e19 0c15 0bba 02ce 0000
    0x0000230: b601 7d2b 190e b802 d32b 3a11 150e 9a00
    0x0000240: 202a b400 8c19 04b6 02d6 b602 da2a 1910
    0x0000250: 1911 ba02 e400 00b6 02e8 57a7 001f 2ab4
    0x0000260: 008c 1904 b602 d615 0db6 02ec 2a19 1019
    0x0000270: 11ba 02f4 0000 b602 e857 2bc1 01d1 9900
    0x0000280: 112a b400 772b c001 d1b9 019d 0200 57b1
    0x0000290:                                        
  Stackmap Table:
    append_frame(@78,Object[#773],Object[#243])
    append_frame(@124,Object[#630])
    full_frame(@223,{Object[#2],Object[#18],Object[#773],Object[#243],Object[#630],Float,Float,Object[#263],Float,Float,Object[#16],Integer},{})
    append_frame(@297,Object[#483])
    same_frame(@301)
    same_locals_1_stack_item_frame(@302,Integer)
    append_frame(@320,Integer,Object[#181])
    same_frame(@354)
    chop_frame(@357,1)
    chop_frame(@372,1)
    same_frame(@402)
    full_frame(@433,{Object[#2],Object[#18],Object[#773],Object[#243],Object[#630],Float,Float,Object[#263],Float,Float,Object[#16],Integer,Object[#483],Integer,Integer},{Object[#9]})
    full_frame(@436,{Object[#2],Object[#18],Object[#773],Object[#243],Object[#630],Float,Float,Object[#263],Float,Float,Object[#16],Integer,Object[#483],Integer,Integer},{Object[#9],Object[#21]})
    append_frame(@470,Object[#303],Object[#7])
    append_frame(@606,Object[#18])
    same_frame(@634)
    full_frame(@655,{Object[#2],Object[#18]},{})

	at net.minecraft.client.audio.SoundHandler.<init>(SoundHandler.java:45) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:446) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$457/1335256857.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.audio.SoundHandler.<init>(SoundHandler.java:45) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:446) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$457/1335256857.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1076502656 bytes (1026 MB) / 2046820352 bytes (1952 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |NONE      |NOSIGNATURE
		mcw-bridges-1.0.5-mc1.16.5-4.jar                  |Macaw's Bridges               |mcwbridges                    |1.0.5               |NONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-4.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-4      |NONE      |NOSIGNATURE
		useful_backpacks-1.16.5-1.12.0.88.jar             |Useful Backpacks              |usefulbackpacks               |1.12.0.88           |NONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		inventorysorter-1.15.2-17.0.0.jar                 |Simple Inventory Sorter       |inventorysorter               |17.0.0              |NONE      |NOSIGNATURE
		SoundControl-1.14.4-0.1.0.0.jar                   |§3Dynamic Surroundings: §eSoun|sndctrl                       |1.14.4-0.1.0.0      |NONE      |NOSIGNATURE
		Environs-1.14.4-0.1.0.0.jar                       |§3Dynamic Surroundings: §eEnvi|environs                      |1.14.4-0.1.0.0      |NONE      |NOSIGNATURE
		u_team_core-1.16.5-3.2.0.194.jar                  |U Team Core                   |uteamcore                     |3.2.0.194           |NONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		jei-1.16.5-7.6.4.88.jar                           |Just Enough Items             |jei                           |7.6.4.88            |NONE      |NOSIGNATURE
		byg-1.1.14.jar                                    |Oh The Biomes You'll Go       |byg                           |1.1.14              |NONE      |NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |NONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		invtweaks-1.16.2-1.0.0.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.2-1.0.0        |NONE      |NOSIGNATURE
		create-mc1.16.5_v0.3.1c.jar                       |Create                        |create                        |mc1.16.5_v0.3.1c+151|NONE      |NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.3.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.3        |NONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |NONE      |NOSIGNATURE
		gravestone-1.16.5-1.0.4.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.4        |NONE      |NOSIGNATURE
		betteranimals-1.16.4-5.5.0.jar                    |Cyber's Better Animal Models  |betteranimals                 |5.5.0               |NONE      |NOSIGNATURE
	Launched Version: 1.16.5-forge-36.1.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.40, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 12x Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz

**Comment by yungnickyoung** [comment]
@RealTenzFate Your crash is due to some problem regarding client-side sound code, which the API doesn't touch. Also, you're mixing mods for various Minecraft versions so.. that's bound to cause some problems.

**Comment by yungnickyoung** [comment]
Closing due to inactivity.
