### ISSUE TITLE
Crash on Quilt 1.19.2

### ISSUE THREAD

**Issue by Gaming32** [YUNG-GANG/YUNGs-API#35]
Loader is Quilt 0.18.1-beta.12. My mods folder contains only four mods: Cloth Config, QFAPI/QSL, YUNG's API, and YUNG's Better Strongholds.

`com.google.gson.JsonParseException: Error loading registry data: Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/structure_type]: yungsapi:yung_jigsaw`

<details>
<summary>Full traceback</summary>

```
com.google.gson.JsonParseException: Error loading registry data: Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/structure_type]: yungsapi:yung_jigsaw
	at net.minecraft.class_5455.method_34849(class_5455.java:298) ~[client-intermediary.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.class_5455.method_30526(class_5455.java:298) ~[client-intermediary.jar:?]
	at net.minecraft.class_5455.method_30519(class_5455.java:292) ~[client-intermediary.jar:?]
	at net.minecraft.class_6903.method_40413(class_6903.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_6903.method_40412(class_6903.java:25) ~[client-intermediary.jar:?]
	at org.quiltmc.qsl.resource.loader.impl.DataPackLoadingContext.loadRegistries(DataPackLoadingContext.java:41) ~[resource-loader-3.0.0-beta.211.19.2.jar.i1.i0:0/:?]
	at net.minecraft.class_525.md7e9ff1$lambda$quilt$applyDefaultDataPacks$4$2(class_525.java:924) ~[client-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.quilt$applyDefaultDataPacks(class_525.java:920) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.redirect$zej000$loadDynamicRegistry(class_525.java:827) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_31130(class_525.java:144) ~[client-intermediary.jar:?]
	at net.minecraft.class_528.method_43462(class_528.java:147) ~[client-intermediary.jar:?]
	at net.minecraft.class_528.<init>(class_528.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_526.method_25426(class_526.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_41843(class_437.java:389) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:380) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1035) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.method_19861(class_442.java:160) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:120) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.method_25402(class_442.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:489) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) [lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1208) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:471) [quilt-loader-0.18.1-beta.12.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.18.1-beta.12.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.18.1-beta.12.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
```

</details>

**Comment by Gaming32** [comment]
This is not an issue with QSL, as it happens without QSL. It's a conflict with Quilt Loader itself.

**Comment by Gaming32** [comment]
Here's an NEC deobfuscated stack trace (mappings are in Yarn, as per Fabric NEC):

<details>
<summary>Deobfuscated stack trace</summary>

```
com.google.gson.JsonParseException: Error loading registry data: Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/structure_type]: yungsapi:yung_jigsaw
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistryManager.method_34849(DynamicRegistryManager:298) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistryManager.load(DynamicRegistryManager:298) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistryManager.load(DynamicRegistryManager:292) ~[?:?]
	at net.minecraft.util.dynamic.RegistryOps.ofLoaded(RegistryOps:32) ~[?:?]
	at net.minecraft.util.dynamic.RegistryOps.ofLoaded(RegistryOps:25) ~[?:?]
	at org.quiltmc.qsl.resource.loader.impl.DataPackLoadingContext.loadRegistries(DataPackLoadingContext.java:41) ~[resource-loader-3.0.0-beta.211.19.2.jar.i1.i0:0/:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.md4ff1a4$lambda$quilt$applyDefaultDataPacks$4$2(CreateWorldScreen:924) ~[?:?]
	at net.minecraft.server.SaveLoading.load(SaveLoading:24) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.quilt$applyDefaultDataPacks(CreateWorldScreen:920) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.redirect$zfd000$loadDynamicRegistry(CreateWorldScreen:827) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.create(CreateWorldScreen:144) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget.loadLevels(WorldListWidget:147) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget.<init>(WorldListWidget:91) ~[?:?]
	at net.minecraft.client.gui.screen.world.SelectWorldScreen.init(SelectWorldScreen:65) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.clearAndInit(Screen:389) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.init(Screen:380) ~[?:?]
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:1035) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.method_19861(TitleScreen:160) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:43) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:120) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.mouseClicked(TitleScreen:343) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:489) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:222) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1208) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main:51) [client-intermediary.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:471) [quilt-loader-0.18.1-beta.12.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.18.1-beta.12.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.18.1-beta.12.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
```
</details>

**Comment by yungnickyoung** [comment]
Sorry, but I don't currently support the Quilt loader explicitly. It's my understanding that Quilt is intended to be compatible with Fabric mods, so the onus is on Quilt to make that guarantee. Kinda weird that it's having issues registering my structure_type, given I use purely vanilla means to do so (I believe)

**Comment by Gaming32** [comment]
Actually Quilt fixed this about a week ago lol

**Comment by SettingDust** [comment]
> It turns out the reflections library assumes all classes are loaded from jar files, which is a bit unfortunate since we don't.

https://github.com/QuiltMC/quilt-loader/issues/139#issuecomment-1328318652
