### ISSUE TITLE
Thread issue with C2ME (yungsapi_fabric.mixins.json)

### ISSUE THREAD

**Issue by Yucked** [YUNG-GANG/YUNGs-API#45]
Any idea what I can do to temporarily fix it?

```java

[03:44:56] [C2ME worker #2/WARN]: Failed to deserialize component: unregistered key the_bumblezone:player_component
[03:44:56] [C2ME worker #2/ERROR]: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: C2ME worker #2)
This is usually NOT a bug in C2ME, but a bug in another mod or in vanilla code. 
Possible solutions: 
  - Find possible causes in the stack trace below and 
    - if caused by another mod, report this to the corresponding mod authors 
    - if no other mods are involved, report this to C2ME 
java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: C2ME worker #2)
	at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:55) ~[c2me-fixes-worldgen-threading-isalpha.10.51-121415ceb1ec8dde.jar:?]
	at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38) ~[c2me-fixes-worldgen-threading-isalpha.10.51-121415ceb1ec8dde.jar:?]
	at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:86) ~[c2me-fixes-worldgen-threading-isalpha.10.51-121415ceb1ec8dde.jar:?]
	at net.minecraft.class_6566.method_43048(class_6566.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_4466$class_4472.<init>(class_4466.java:849) ~[server-intermediary.jar:?]
	at net.minecraft.class_4466.method_5959(class_4466.java:216) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.<init>(net/minecraft/class_1308.java:149) ~[server-intermediary.jar:?]
	at net.minecraft.class_1314.<init>(class_1314.java:14) ~[server-intermediary.jar:?]
	at net.minecraft.class_1296.<init>(class_1296.java:29) ~[server-intermediary.jar:?]
	at net.minecraft.class_1429.<init>(net/minecraft/class_1429.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.class_4466.<init>(class_4466.java:175) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_5883(class_1299.java:544) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_17846(class_1299.java:548) ~[server-intermediary.jar:?]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at net.minecraft.class_1299.method_5892(class_1299.java:548) ~[server-intermediary.jar:?]
	at net.minecraft.class_3499.yungsapi_getEntity(com/yungnickyoung/minecraft/yungsapi/mixin/EntityProcessorMixin.java [yungsapi_fabric.mixins.json]:126) ~[server-intermediary.jar:?]
	at net.minecraft.class_3499.handler$bmd000$yungsapi$processEntities(com/yungnickyoung/minecraft/yungsapi/mixin/EntityProcessorMixin.java [yungsapi_fabric.mixins.json]:62) ~[server-intermediary.jar:?]
	at net.minecraft.class_3499.method_15172(net/minecraft/class_3499.java:346) ~[server-intermediary.jar:?]
	at net.minecraft.class_3781.method_16626(net/minecraft/class_3781.java:122) ~[server-intermediary.jar:?]
	at net.minecraft.class_3790.method_27236(net/minecraft/class_3790.java:89) ~[server-intermediary.jar:?]
	at net.minecraft.class_3790.method_14931(net/minecraft/class_3790.java:85) ~[server-intermediary.jar:?]
	at net.minecraft.class_3449.method_14974(net/minecraft/class_3449.java:100) ~[server-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(net/minecraft/class_2794.java:320) ~[server-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(net/minecraft/class_2794.java:319) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(net/minecraft/class_2806.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.md3c58b9$c2me-threading-worldgen$lambda$runGenerationTask$0$5(com/ishland/c2me/threading/worldgen/mixin/MixinChunkStatus.java [c2me-threading-worldgen.mixins.json]:108) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]


```

**Comment by yungnickyoung** [comment]
Sorry for the very late response lol. Given this is related to bee behavior, I'd wager it's an old bug with bumblezone that should be fixed now.
