### ISSUE TITLE
YungsAPI listed as not installed, but it is?

### ISSUE THREAD

**Issue by khorvo77** [YUNG-GANG/YUNGs-API#5]
MultiMC version: 0.6.12-1530
Forge 36.1.0
Minecraft 1.16.5

Crash report: 

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 5/15/21 8:40 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.18-launcher.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[forge:?] {re:classloading}
-- MOD bettermineshafts --
Details:
	Mod File: BetterMineshafts-Forge-1.16.4-2.0.3.jar
	Failure message: Mod bettermineshafts requires yungsapi 1.16.4-Forge-3 or above
		Currently, yungsapi is not installed
	Mod Version: 1.16.4-2.0.3
	Mod Issue URL: https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/issues
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.18-launcher.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

-- MOD wailaharvestability --
Details:
	Mod File: WailaHarvestability-mc1.16.x-forge-1.1.15.jar
	Failure message: Mod wailaharvestability requires waila 1.10 or above
		Currently, waila is not installed
	Mod Version: 1.1.15
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

-- MOD bettercaves --
Details:
	Mod File: BetterCaves-Forge-1.16.4-1.1.2.jar
	Failure message: Mod bettercaves requires yungsapi 1.16.4-Forge-2 or above
		Currently, yungsapi is not installed
	Mod Version: 1.16.4-1.1.2
	Mod Issue URL: https://github.com/yungnickyoung/YUNGs-Better-Caves/issues
	Exception message: MISSING EXCEPTION MESSAGE

-- MOD valhelsia_structures --
Details:
	Mod File: valhelsia_structures-1.16.5-0.1.0.jar
	Failure message: Mod valhelsia_structures requires valhelsia_core 16.0.7 or above
		Currently, valhelsia_core is not installed
	Mod Version: 1.16.5-0.1.0
	Mod Issue URL: https://github.com/stal111/Valhelsia-Structures/issues
	Exception message: MISSING EXCEPTION MESSAGE

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1662710280 bytes (1585 MB) / 3151495168 bytes (3005 MB) up to 7397179392 bytes (7054 MB)
	CPUs: 12
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx7936m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.18-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.18-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.18-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.18-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.5-0.5.5.jar OptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.5-0.5.5.jar optiforge TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.18-launcher.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.5-0.5.5.jar optiforgewrapper TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.18
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.18-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |NONE      |NOSIGNATURE
		forge-1.16.5-36.1.18-universal.jar                |Forge                         |forge                         |36.1.18             |NONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90

**Comment by khorvo77** [comment]
Sorry, Modlist: 

Mods:
  [✔️] [1.16.5]+SecurityCraft+v1.8.21.1
  [✔️] abnormals_core-1.16.5-3.1.1
  [✔️] absentbydesign-1.16.5-1.4.1
  [✔️] additional_lights-1.16.4-2.1.3
  [✔️] Adorn-1.13.1+1.16.4-forge
  [✔️] AdPoles-1.16.4-5.0.4.0-build.0095
  [✔️] alexsmobs-1.10.1
  [✔️] AmbientSounds_v3.1.6_mc1.16.5
  [✔️] AppleSkin-mc1.16.2-forge-1.0.14
  [✔️] Aquaculture-1.16.5-2.1.18
  [✔️] Architects-Palette-1.16.4-1.1.3
  [✔️] areas_1.16.5-2.2
  [✔️] Artifacts-1.16.5-2.8.4
  [✔️] astikorcarts-1.16.5-1.1.1
  [✔️] AutoRegLib-1.6-47
  [✔️] backslot-1.16.3-1.2.0.0
  [✔️] bettas-1.2.1
  [✔️] BetterAdvancements-1.16.5-0.1.0.105
  [✔️] betteranimals-1.16.4-5.5.0
  [✔️] betteranimalsplus-1.16.5-10.2.0
  [✔️] BetterBurning-1.16.5-6.0.5
  [✔️] BetterCaves-Forge-1.16.4-1.1.2
  [✔️] betterendforge-1.16.4-1.6.0
  [✔️] BetterMineshafts-Forge-1.16.4-2.0.3
  [✔️] bigbrain-1.2.3
  [✔️] BiomesOPlenty-1.16.5-13.1.0.465-universal
  [✔️] Bookshelf-1.16.5-10.0.7
  [✔️] BotanyPots-1.16.5-7.0.17
  [✔️] Bountiful-1.16.4-3.3.1
  [✔️] buildersaddition-1.16.5-20210421a
  [✔️] buzzier_bees-1.16.5-3.0.1
  [✔️] byg-1.2.7
  [✔️] camera-1.16.5-1.0.2
  [✔️] carryon-1.16.5-1.15.3.13
  [✔️] catjammies-1.1.0
  [✔️] charm-forge-1.16.4-2.1.1-hotfix3
  [✔️] charms-1.2.1
  [✔️] chiselsandbits-0.3.4-RELEASE
  [✔️] citadel-1.6.3
  [✔️] CNB-1.16.3_5-1.2.11
  [✔️] cobbler-1.6.1
  [✔️] collective-1.16.5-2.26
  [✔️] comforts-forge-1.16.4-4.0.1.0
  [✔️] CookingForBlockheads_1.16.5-9.3.1
  [✔️] corpse-1.16.4-1.0.6
  [✔️] CraftTweaker-1.16.5-7.1.0.284
  [✔️] create-mc1.16.5_v0.3.1c
  [✔️] CreativeCore_v2.1.3_mc1.16.5
  [✔️] CrockPot-1.16.3-1.4.0-release
  [✔️] crumbs-forge-1.0.7
  [✔️] CTM-MC1.16.1-1.1.2.6
  [✔️] curios-forge-1.16.5-4.0.5.1
  [✔️] Curious+Armor+Stands-1.16.5-2.1.0
  [✔️] customizableelytra-1.16.4-1.4.4
  [✔️] decorative_blocks-1.16.4-1.7.2
  [✔️] differentiate-1.16.5-0.4.0
  [✔️] DoggyTalents-1.16.5-2.0.1.6
  [✔️] DummyPlayers-1.0.0-release+1
  [✔️] DungeonCrawl-1.16.3-2.2.4
  [✔️] dungeons_gear-1.16.4-3.0.13-hotfix
  [✔️] dungeons_mobs-1.16.4-1.0.4
  [✔️] dungeonsarise1.16.5-1.2.68a-HF
  [✔️] DustrialDecor-1.1.6
  [✔️] DynamicSurroundings-1.16.4-4.0.4.2
  [✔️] eidolon-0.2.7
  [✔️] embellishcraft-1.16.4-3.3.0.0
  [✔️] embellishcraft-bop-1.16.4-3.3.0
  [✔️] emojiful-1.16.4-2.1.4
  [✔️] EnchantmentDescriptions-1.16.5-7.0.8
  [✔️] endergetic-1.16.4-3.0.0
  [✔️] EndRemastered-R36
  [❌] EpicFightMod-1.16.5-3.2.2.jar (disabled)
  [✔️] extlights-3.3
  [✔️] Extractures(v1.2)_1.16.4
  [✔️] fairylights-4.0.5-1.16.5
  [✔️] FarmersDelight-1.16.5-0.4.3
  [✔️] FastLeafDecay-v25
  [✔️] fins-1.4.1
  [✔️] fishtraps-0.1.3
  [✔️] flamboyant-1.16.5-1.4.1
  [✔️] floormats-1.16.5-v1.4.0
  [✔️] ForgeEndertech-1.16.4-7.1.0.0-build.0075
  [✔️] FriendlyFire-1.16.5-7.0.2
  [✔️] ftb-backups-2.1.1.6
  [✔️] furniture-7.0.0-pre19-1.16.3
  [✔️] geckolib-forge-1.16.5-3.0.35
  [✔️] goblintraders-1.4.0-1.16.3
  [✔️] greekfantasy-16.4.17
  [✔️] guardvillagers-1.16.5.1.2.4
  [📁] hats (folder)
  [✔️] Hats-1.16.5-10.1.0
  [✔️] HunterIllager-1.16.5-1.1.0
  [✔️] Hwyla-forge-1.10.11-B78_1.16.2
  [✔️] iceandfire-2.1.6-1.16.4
  [✔️] iChunUtil-1.16.5-10.2.0
  [❌] ilikewood-1.16.5-6.3.0.0.jar (disabled)
  [✔️] illagersweararmor-1.0.4
  [✔️] ImmersiveEngineering-1.16.5-4.2.4-134
  [✔️] ImmersivePetroleum-1.16.5-3.2.0-3
  [❌] immersive-portals-0.16-mc1.16.5-forge.jar (disabled)
  [✔️] infernal-expansion-forge-1.3
  [✔️] inventoryhotswap-1.16-1.2
  [✔️] ironchest-1.16.4-11.2.10
  [✔️] ItemPhysic_v1.4.18_mc1.16.5
  [✔️] jei-1.16.5-7.7.0.91
  [✔️] Jellyfishing-1.6.9
  [✔️] JustEnoughResources-1.16.4-0.12.0.113
  [✔️] Kiwi-1.16.5-3.5.1
  [✔️] KleeSlabs_1.16.5-9.2.1
  [✔️] kotlinforforge-1.12.0-obf
  [✔️] looot-1.16.4-1.0.0.3
  [✔️] lootr-1.16.4-0.0.5.17
  [✔️] lostcities-1.16-4.0.9-beta
  [✔️] Mantle-1.16.5-1.6.97
  [✔️] mapperbase-1.16.4-2.3.0.0
  [✔️] mcw-bridges-1.0.5-mc1.16.5-4
  [✔️] mcw-doors-1.0.2-mc1.16.5
  [✔️] mcw-furniture-2.0.1-mc1.16.5
  [✔️] mcw-roofs-2.0.1-mc1.16.5-4
  [✔️] mcw-trapdoors-1.0.2-mc1.16.5
  [✔️] mcw-windows-1.0.3-mc1.16.5
  [✔️] Mekanism-1.16.5-10.0.21.448
  [✔️] MekanismAdditions-1.16.5-10.0.21.448
  [✔️] MekanismGenerators-1.16.5-10.0.21.448
  [✔️] MekanismTools-1.16.5-10.0.21.448
  [✔️] MmmMmmMmmMmm-1.16.5-1.2.0
  [✔️] MoreJellyfish-1.1.5
  [✔️] Morpheus-1.16.5-4.2.70
  [❌] mowziesmobs-1.5.16.jar (disabled)
  [✔️] multibeds-1.16-1.7.9
  [✔️] mysticalworld-1.16.4-0.3.1.10
  [✔️] NaturesCompass-1.16.5-1.8.6
  [✔️] Neat+1.7-27
  [✔️] NefsMedievalPubLite+v0.8.5(1.16.5)
  [✔️] neoncraft-2.1
  [✔️] netheritehorsearmor-1.7
  [✔️] notenoughcrashes-3.2.0-forge
  [✔️] Notes-1.16.5-1.2.3
  [✔️] obfuscate-0.6.1-1.16.3
  [✔️] OffHandCombat-1.16.3-3.2.0.3
  [✔️] OptiFine_1.16.5_HD_U_G8
  [✔️] overloadedarmorbar-5.1.0
  [✔️] Paraglider-1.16.5-1.3.1.1
  [✔️] Patchouli-1.16.4-51
  [✔️] physics-mod-1.3.4_forge
  [✔️] pitg-1.16.3-1.4.2
  [✔️] Placebo-1.16.4-4.4.2
  [✔️] platforms-1.16-1.7.11
  [✔️] polymorph-forge-1.16.5-0.24
  [✔️] productivebees-1.16.5-0.6.9.11
  [✔️] projectvibrantjourneys-1.16.5-3.0.3
  [✔️] QuarkOddities-1.16.3
  [✔️] QuarkOPlenty-1.16.5-1.2.1
  [✔️] Quark-r2.4-311
  [✔️] randompatches-2.4.4-forge
  [✔️] randomvillagenames_1.16.5-1.1
  [✔️] ratlantis-1.0.0-1.16.3
  [✔️] rats-7.1.1-1.16.5
  [✔️] reap-1.16.5-1.0.1
  [✔️] refinedstorage-1.9.12
  [✔️] refinedstorageaddons-0.7.2
  [✔️] Regrowth-1.16.4-1.16.4-1.35.0.18
  [✔️] repurposed_structures-1.16.5-2.6.6-forge
  [✔️] SaveYourPets-1.16.2-1.0.0.5
  [✔️] secretrooms-1.16.5-1.0.1
  [✔️] shetiphiancore-1.16-3.8.5
  [✔️] simplefarming-1.16.4-1.3.5
  [✔️] sit-1.16.5-v1.3.1
  [✔️] SkinnedCarts-1.16.2-1.1.1
  [✔️] SnowRealMagic-1.16.4-2.5.7
  [✔️] snowundertrees-1.16.5-v1.1.4
  [✔️] Space-Bosstools-1.16.5-5.1
  [✔️] SpartanShields-1.16.5-2.1.2
  [✔️] spiders-2.0-1.16.4-1.0.4
  [✔️] StorageDrawers-1.16.3-8.2.2
  [✔️] structure_gel-1.16.5-1.7.7
  [✔️] supplementaries-1.16.5-0.12.1
  [✔️] swingthroughgrass-1.16.4-1.5.3
  [✔️] switchbow-1.7
  [✔️] TConstruct-1.16.5-3.0.3.152
  [✔️] TerraForged-1.16.5-0.2.10
  [✔️] TheAbyss2+1.9.7+1.16.5
  [✔️] the-conjurer-1.16.4-1.0.13
  [✔️] Toast-Control-1.16.4-4.3.1
  [✔️] torchslabmod-1.16.4_v1.6.19
  [✔️] towers_of_the_wild-1.16.4-2.0.1
  [✔️] travelers_index-1.16.4-1.0.2
  [✔️] tumbleweed-1.16-0.4.9
  [✔️] tux-1.16.4-1.0
  [✔️] twilightforest-1.16.5-4.0.435-universal
  [✔️] twoplayersonehorse-1.16.4-2.0.2
  [✔️] valhelsia_core-16.0.8
  [✔️] valhelsia_structures-1.16.5-0.1.0
  [✔️] villagernames_1.16.5-2.9
  [✔️] WailaHarvestability-mc1.16.x-forge-1.1.15
  [✔️] walljump-forge-1.16.4-1.3.7
  [✔️] WaterStrainer-1.16.3-10.0.0
  [✔️] WAWLA-1.16.5-8.0.1
  [✔️] Waystones_1.16.5-7.5.1
  [✔️] workshopsofdoom-1.16.4-1.1.0.1
  [✔️] worldedit-mod-7.2.5-dist
  [✔️] WorldPreGenerator-1.16.5-2.0.0
  [✔️] Xaeros_Minimap_21.8.1_Forge_1.16.5
  [✔️] XaerosWorldMap_1.13.5_Forge_1.16.5
  [✔️] xlpackets-1.1
  [✔️] YungsApi-1.16.4-Forge-6

**Comment by yungnickyoung** [comment]
Try redownloading my mods. Something is probably wrong with your modded environment, as checking dependencies is the responsbility of Forge, not my mods. Also, you are missing WAILA and Valhelsia Core.

**Comment by yungnickyoung** [comment]
Closing due to inactivity. If you continue to have this issue, feel free to open a new report!
