### ISSUE TITLE
1.20.6 work with 1.21? #1584

### ISSUE THREAD

**Issue by Nhantaa** [YUNG-GANG/YUNGs-API#73]
you have created version 1.21, but is version 1.20.6 compatible with version 1.21?

**Comment by imeesa** [comment]
The version for 1.20.6 won't run on 1.21, it just wasn't made for it.

**Comment by Nhantaa** [comment]
> The version for 1.20.6 won't run on 1.21, it just wasn't made for it.

In that case, why create version 1.21 before version 1.20.6? It makes no sense.

**Comment by imeesa** [comment]
> In that case, why create version 1.21 before version 1.20.6? It makes no sense.
Because more people want it.

**Comment by MimzyFang** [comment]
> > The version for 1.20.6 won't run on 1.21, it just wasn't made for it.
> 
> In that case, why create version 1.21 before version 1.20.6? It makes no sense.

1.21 was released 1 month after 1.20.6 so a lot of mods did not brother with updating to 1.20.6 and just skipped it

**Comment by HIM049** [comment]
But looks this mod with version 1.20.4 cannot working on 1.20.6? Because my server is crashed when try to load it.
> [01:20:12] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.AbstractMethodError: Receiver class com.yungnickyoung.minecraft.yungsapi.module.StructureTypeModule$$Lambda/0x0000000022ab9000 does not define or inherit an implementation of the resolved method 'abstract com.mojang.serialization.MapCodec codec()' of interface net.minecraft.class_7151.
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.10.jar:?]
Caused by: java.lang.AbstractMethodError: Receiver class com.yungnickyoung.minecraft.yungsapi.module.StructureTypeModule$$Lambda/0x0000000022ab9000 does not define or inherit an implementation of the resolved method 'abstract com.mojang.serialization.MapCodec codec()' of interface net.minecraft.class_7151.
        at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88) ~[?:?]
        at knot/com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$4(KeyDispatchCodec.java:46) ~[datafixerupper-7.0.14.jar:?]
        at knot/com.mojang.serialization.DataResult$Success.flatMap(DataResult.java:194) ~[datafixerupper-7.0.14.jar:?]
        at knot/com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:45) ~[datafixerupper-7.0.14.jar:?]
        at knot/com.mojang.serialization.MapDecoder.lambda$compressedDecode$1(MapDecoder.java:52) ~[datafixerupper-7.0.14.jar:?]

**Comment by HIM049** [comment]
But looks this mod with version 1.20.4 cannot working on 1.20.6? Because my server is crashed when try to load it.

**Comment by yungnickyoung** [comment]
Sorry, my mods don't support 1.20.6 and we're not planning on porting to it due to time constraints.
