### ISSUE TITLE
the api is crashing the launcher

### ISSUE THREAD

**Issue by phonixpeaceful** [YUNG-GANG/YUNGs-API#77]
when i launch fabric it crashes because the api

**Comment by phonixpeaceful** [comment]
-1

**Comment by HIM049** [comment]
I think I have same question with you, My server version is 1.20.6.

CRASH LOG:
> [01:20:12] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.AbstractMethodError: Receiver class com.yungnickyoung.minecraft.yungsapi.module.StructureTypeModule$$Lambda/0x0000000022ab9000 does not define or inherit an implementation of the resolved method 'abstract com.mojang.serialization.MapCodec codec()' of interface net.minecraft.class_7151.
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.10.jar:?]
Caused by: java.lang.AbstractMethodError: Receiver class com.yungnickyoung.minecraft.yungsapi.module.StructureTypeModule$$Lambda/0x0000000022ab9000 does not define or inherit an implementation of the resolved method 'abstract com.mojang.serialization.MapCodec codec()' of interface net.minecraft.class_7151.
        at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88) ~[?:?]
        at knot/com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$4(KeyDispatchCodec.java:46) ~[datafixerupper-7.0.14.jar:?]
        at knot/com.mojang.serialization.DataResult$Success.flatMap(DataResult.java:194) ~[datafixerupper-7.0.14.jar:?]
        at knot/com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:45) ~[datafixerupper-7.0.14.jar:?]
        at knot/com.mojang.serialization.MapDecoder.lambda$compressedDecode$1(MapDecoder.java:52) ~[datafixerupper-7.0.14.jar:?]

**Comment by yungnickyoung** [comment]
Sorry, 1.20.6 is not supported for my mods.
